### ISSUE TITLE
beta problem

### ISSUE THREAD

**Issue by wiz4rdfb** [andrewwiik/IntelixBeta#10]
İntelix 1.27
![a653deb8-aa99-42fb-84ff-d7bb907b3235](https://user-images.githubusercontent.com/38587280/39084979-9872e9d8-4585-11e8-8cf4-2f0e6a8576c2.png)

İntelix(beta) 1.3.3
![c5308ceb-1a18-449d-8dfa-feea9de50409](https://user-images.githubusercontent.com/38587280/39084998-cf71e88a-4585-11e8-8574-eb4349d8b94c.png)

**Comment by andrewwiik** [comment]
Not seeing the problem

**Comment by andrewwiik** [comment]
Notifications not in the history section don't get grouped on purpose

**Comment by wiz4rdfb** [comment]
will it no longer appear in the first statement
