### ISSUE TITLE
Doesn’t group new notifications

### ISSUE THREAD

**Issue by kskumar9663** [andrewwiik/IntelixBeta#13]
It groups notifications that are already there. But any notifications that come in after the tweak has been installed are not grouped.

**Comment by aki91196** [comment]
Yeah it’s true

**Comment by NICHOLAS85** [comment]
This Beta version of Intelix ungroups recent notifications purposely. Once the notifications are moved into history by locking/unlocking they’ll be grouped. Use the non-beta version to have all your notifications grouped.
