### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by gokmenecer** [andrewwiik/IntelixBeta#8]
In version 1.3, this was the notifications.
![img_0258](https://user-images.githubusercontent.com/14973945/39082275-1754e076-4559-11e8-8284-3bfbd6bb8c53.PNG)
But in version 1.3.3 it became normal
![img_0259](https://user-images.githubusercontent.com/14973945/39082276-2703d86a-4559-11e8-92aa-596331ba03d1.PNG)

**Comment by andrewwiik** [comment]
The notification header being invisible in 1.3 was a bug, it being back was the correct fix
